generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: AmazonPHP\SellingPartner
  srcBasePath: src/AmazonPHP/SellingPartner
  variableNamingConvention: camelCase
  modelPackage: Model\FBAInboundEligibility
  packageName: FBAInboundEligibilitySDK
files:
  api.mustache:
    templateType: API
    destinationFilename: /FBAInboundEligibilitySDK.php
